number1 = int(input("type number:"))
number2 = int(input("type number:"))
print(number1 + number2)
print(number1 - number2)
print(number1 / number2)
print(number1 // number2)
print(number1 % number2)
print(number1 * number2)
